<?php

use Drupal\Core\Link;
use Drupal\language\Entity\ConfigurableLanguage;
use Drupal\Core\Language\Language;
use Drupal\Core\Url;

/**
 * @file
 * Functions to support theming in the umdlib theme.
 */

/**
 * Implements template_preprocess_image().
 */
function umdlib_umdds_preprocess_image(&$variables) : void {
  if (!empty($variables['attributes'])) {
    if (!empty($variables['attributes']['height'])) {
      unset($variables['attributes']['height']);
    }
    if (!empty($variables['attributes']['width'])) {
      unset($variables['attributes']['width']);
    }
  }
}


/**
 * Implements hook_preprocess_breadcrumb() for node.html.twig.
 */
function umdlib_umdds_preprocess_breadcrumb(&$variables) {
  $request = \Drupal::request();
  $route_match = \Drupal::routeMatch();

  if (($node = $route_match->getParameter('node')) && $variables['breadcrumb']) {
    if (is_numeric($node)) {
      $node = Node::load($node);
    }
    $variables['breadcrumb'][] = [
      'text' => $node->getTitle(),
    ];
  } else {
    $page_title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());

    if (!empty($page_title)) {
      $variables['breadcrumb'][] = [
        'text' => $page_title,
      ];
    }
  }
  $variables['#cache']['contexts'][] = 'url';
}

/**
 * Prepares links for menus
 *
 * @param array $variables
 *   An associative array containing:
 *   - media: An individual media for display.
 */
function umdlib_umdds_preprocess_links(&$variables) {
  $links = $variables['links'];
  if (!empty($links)) {
    $variables['links'] = [];
    $lang_man = \Drupal::service('language_manager');
    foreach ($links as $key => $link) {
      $item = $link;
      if (!empty($item['link'])) {
        if (!empty($item['link']['#options']['language'])) {
          $lang = $item['link']['#options']['language'];
          $lang_id = $lang->getId();
          $lang_name = $lang->getName();
          $item['lang_name'] = $lang_name;
          $item['lang_id'] = $lang_id;
          switch ($lang_id) {
            case "en":
              $item['nationAbbreviation'] = "US";
              $item['nation'] = "USA";
              $item['nativeName'] = "English";
              break;
            case "ja":
              $item['nationAbbreviation'] = "JP";
              $item['nation'] = "Japan";
              $item['nativeName'] = "日本語";
              break;
          }
          if (!empty($lang_id) && !empty($item['link']['#url'])) {
            $current_lang = $lang_man->getLanguage($lang_id);
            $url = $item['link']['#url'];
            $uri_string = $url->toUriString();
            $url_opts = ['language' => $current_lang];
            $new_url = $url::fromUri($uri_string, $url_opts);
            $item['href'] = $new_url->toString();
          }
        }
      }
      // Add the item to the list of links.
      $variables['links'][$key] = $item;
    }
  }
}